AWSTemplateFormatVersion: '2010-09-09'
Description: Parent CloudFormation template to create 200 S3 buckets via nested stacks
Resources:
  BucketStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child-bucket.yaml
      Parameters:
        BucketName: curtistest120585-1
 